INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('TOLGA', 'TA1TLA', 'Gaziosmanpaşa', 'Teksilkent Çevirimiçi Yetkilisi');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ŞEREF', 'TA2DJD', 'ÇAMLICA', 'Ataşehir yeni sahrada çalışıyor');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ÇINAR', 'TB2CCI', 'KADIKÖY', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('EBRAR', 'TA1EBR', 'ARNAVUTKÖY', 'AFAD Yetkili');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ARAS', 'TA1KCR', 'GÜNGÖREN', 'Elektronikci Gps modüller ile ilgileniyor');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('İSMAİL', 'TA1IWR', 'GAZİOSMANPAŞA', 'Elektronik Mühendisi');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ÖKKEŞ / ASYA', 'TA1KKS', 'EYÜP', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ERTUĞRUL', 'TB2EEB', 'TUZLA', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ADEM', 'TA1DUS', 'LEVENT', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('RECEP', 'TA1BAK', 'Küçükçekmece', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('DOĞAN', 'TA1GO', 'BAYRAMPAŞA', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ŞABAN', 'TA1KDS', 'Avcılar', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('KERİM', 'TA1KB', 'SARIYER', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('KAAN', 'TB2KKD', 'Maltepe', 'LPT (Master) (Licensed Penetration Tester)');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('LEVENT', 'TA0V', 'BÜYÜKADA', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('MEHMET', 'TA0AAK', 'KINALIADA', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ZEYNEL', 'TA0ACL', 'HEYBELİADA', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ARAS', 'TA0ARS', 'BÜYÜKADA', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ÖZDEMİR', 'TA0OZY', 'BÜYÜKADA', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ŞÜKRÜ', 'TA1K', 'SARIYER', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ARMAN', 'TA1DC', 'ŞİŞLİ', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('FARUK', 'TA1MB', 'BAŞAKŞEHİR', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('DOĞU', 'TA1ND', 'FERİKÖY', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('METİN', 'TA1NN', 'SULTANGAZİ', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('EROL', 'TA1QQ', 'AVCILAR', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('OĞUZ', 'TA1XO', 'BAHÇELİEVLER', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ERCÜMENT', 'TA1AJQ', 'BAHCELİEVLER', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('OZAN / ALİ MERT', 'TA1BAR', 'SARIYER', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('İLHAN', 'TA1BBE', 'HALKALI', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ATIL', 'TA1BBN', 'SARIYER', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('TOPRAK', 'TA1BUT', 'GÖKTÜRK', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('MUSTAFA', 'TA1BYS', 'GAZİOSMANPAŞA', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ENGİN', 'TA1CCS', 'TAKSİM', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('HAMZA', 'TA1CMR', 'SARIYER', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('SEFER', 'TA1CSK', 'KÜÇÜKÇEKMECE', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('MESUT', 'TA1DAL', 'KURTULUŞ', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('DANYAL', 'TA1DAN', 'SARIYER', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('BORA', 'TA1DBX', 'İKİTELLİ', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('TURABİ', 'TA1DEV', 'KAĞITHANE', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('NURETTİN', 'TA1DLD', 'ARNAVUTKÖY', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('UĞUR', 'TA1EGK', 'CENNET MАН.', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ERAY', 'TA1ENR', 'TEKSTİLKENT', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ÜMİT', 'TA1ETS', 'GÜNGÖREN', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ERKAN', 'TA1FIK', 'BAHÇELİEVLER', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('FATİH', 'TA1FTH', 'BAYRAMPAŞA', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('GÖKHAN', 'TA1GBB', 'ESENYURT', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('AKİF', 'TA1GMH', 'YENİBOSNA', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ARDA', 'TA1KAI', 'BAYRAMPAŞA', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ŞABAN', 'TA1KPS', 'AVCILAR', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ERAY', 'TA1KRJ', 'MECİDİYEKÖY', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('İLKAN', 'TA1LRA', 'EYÜP', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('MERVE', 'TA1MMD', 'KURTULUŞ', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('MEHDİ', 'TA1MML', 'KÜCÜKÇEKMECE', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('MURAT', 'TA1MRZ', 'BAŞAKŞEHİR', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('FATİH', 'TA1NAX', 'GAZİOSMANPAŞA', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('NAZMİ', 'TA1NZM', 'SULTANGAZİ', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ÖZGÜR', 'TA1OBZ', 'BAŞAKŞEHİR', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('BATUHAN', 'TA1PGS', 'EYÜP', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('RECEP', 'TA1RAK', 'KÜÇÜKÇEKMECE', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ALP', 'TA1REN', 'KÜÇÜKÇEKMECE', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('SEMRA', 'TA1RSS', 'SARIYER', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('AYHAN', 'TA1SEF', 'EYÜP', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('SUPHİ', 'TA1SPH', 'BAYRAMPAŞA', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('SERTAN', 'TA1STN', '4.LEVENT', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('İLKER', 'TA1TCL', 'KAĞITHANE', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ÜMİT', 'TA1TMU', 'BEYOĞLU', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('EMRE', 'TA1TUX', 'RAMİ', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('YUNUS EMRE', 'TA1VUS', 'BAYRAMPAŞA', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('BORAN', 'TA1WLA', 'KÜÇÜKÇEKMECE', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('CENGİZ', 'TA1WSW', 'ESENLER', 'OSCP (Offensive Security Certified Professional)');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('TALHA', 'TA1WZM', 'BAHÇELİEVLER', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('AYTAÇ', 'TA1ZAI', 'BAKIRKÖY', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('GÖKSEL', 'TB1BAN', 'KÜÇÜKÇEKMECE', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ORHAN', 'TB1BTB', 'BOĞAZİÇİ ÜNİ.', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('EBRU / HİRANUR', 'TB1EBU', 'ESENYURT', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('MUHİTTİN', 'TB1GOP', 'GAZİOSMANPAŞA', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('BURAK', 'TB1KRS', 'KÜÇÜKÇEKMECE', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('HÜSEYİN', 'TB1KST', 'ARNAVUTKÖY', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('MUHAMMET', 'TB1MCM', 'EYÜP', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('TÜRKER', 'TB1MGA', 'GAZİOSMANPAŞA', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('SÜLEYMAN', 'TB1OZT', 'FATİH', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('TURHAN', 'TB1RRT', 'EYÜP', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('SİNAN', 'TB1SNN', 'GÜNGÖREN', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('TARIK', 'TB1TAR', 'GÜNGÖREN', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('SELİM', 'TB1TUZ', 'GAZİOSMANPAŞA', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('TAMER', 'TA2CF', 'GÖZTEPE', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('HAMZA', 'TA2HY', 'K. EREĞLİ', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('MUST MUSTAFA', 'TA2MV', 'BEYKOZ', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('EFE', 'TA2ZU', 'İDEALTEPE', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('EVREN', 'TA2BAQ', 'MALTEPE', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('CAHİT', 'TA2CHI', 'KADIKÖY', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('MUSTAFA GOKHAN', 'TA2CNQ', 'ÜSKÜDAR', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('İSHAK', 'TA2DIE', 'BEYKOZ', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('DAVUT', 'TA2DRR', 'KARTAL', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ERCÜMENT', 'TA2EIZ', 'KADIKÖY', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ERCAN', 'TA2ERC', 'ÇEKMEKÖY', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('UFUK', 'TA2FUK', 'ÜSKÜDAR', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('AYBERK', 'TA2KRN', 'BAŞAKŞEHİR', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('LEVENT', 'TA2LTE', 'ATAŞEHİR', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('MURAT', 'TA2MZP', 'KÜÇÜKÇEKMECE', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ZEKERİYA', 'TA2MZS', 'DUDULLU', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('SABRİ', 'TA2NJS', 'PENDİK', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ÖMER / BARIŞ', 'TA2OCP', 'KADIKÖY', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('OLCAY', 'TA2OLZ', 'TUZLA', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('İLKER / YAĞMUR', 'TA2PYZ', 'MALTEPE', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ALİ', 'TA2RTC', 'ÜSKÜDAR', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('RÜKNETTİN', 'TA2RYR', 'ÜSKÜDAR', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('SERDAR', 'TA2SRI', 'ÜSKÜDAR', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('OĞUZHAN', 'TA2TTJ', 'ADAPAZARI', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('SEYFULLAH', 'TA2ZSK', 'ÇAMLICA', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('FURKAN', 'TB2BBV', 'ÇAMLICA', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ÖMER', 'TB2ELD', 'YALOVA', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('BARIŞ', 'TB2SJB', 'ATAŞEHİR', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('MEHMET', 'TB2SLN', 'MALTEPE', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('İLHAN', 'TA3TBB', 'BURSA', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('ERDENER', 'TA3TER', 'FLORYA', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('YİĞİT', 'TA3TTZ', 'KADIKÖY', '');
INSERT OR IGNORE INTO operatorler (operator, cagri_isareti, qth, hakkinda) VALUES ('İBRAHİM', 'TB3MDL', 'BURSA', '');
